# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-20 21:10
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('somoapp', '0002_auto_20170419_0110'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='upload',
            field=models.FileField(default=django.utils.timezone.now, upload_to=b''),
            preserve_default=False,
        ),
    ]
