# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-22 21:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('somoapp', '0003_book_upload'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='semester',
            field=models.CharField(max_length=7),
        ),
        migrations.AlterField(
            model_name='book',
            name='year',
            field=models.CharField(max_length=7),
        ),
    ]
