# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-23 07:54
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('somoapp', '0007_auto_20170423_0750'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='useraccount',
            name='user',
        ),
    ]
