# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-23 12:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('somoapp', '0009_useraccount_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserAccountUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('book', models.ManyToManyField(to='somoapp.UserAccount')),
            ],
        ),
    ]
