# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-23 12:38
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('somoapp', '0010_useraccountuser'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='useraccountuser',
            name='book',
        ),
        migrations.DeleteModel(
            name='UserAccountUser',
        ),
    ]
